/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/react-app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#e6e8ee",
        "tertiary-fixed-dim": "#00d4ec",
        "primary-fixed": "#809bff",
        "on-secondary-container": "#5000d2",
        "on-tertiary-container": "#004d57",
        "secondary-dim": "#5819db",
        "outline": "#75777b",
        "on-primary-container": "#001b61",
        "surface": "#f5f6fb",
        "surface-variant": "#dadde4",
        "primary-container": "#809bff",
        "on-primary-fixed": "#000000",
        "on-secondary-fixed-variant": "#591bdc",
        "on-error-container": "#510017",
        "error": "#b41340",
        "inverse-surface": "#0c0e12",
        "secondary": "#652fe7",
        "surface-container-low": "#eff1f6",
        "surface-bright": "#f5f6fb",
        "surface-container-highest": "#dadde4",
        "primary-fixed-dim": "#6c8cff",
        "surface-tint": "#004be2",
        "error-container": "#f74b6d",
        "on-background": "#2c2f33",
        "error-dim": "#a70138",
        "primary-dim": "#0041c7",
        "tertiary-fixed": "#00e3fd",
        "surface-dim": "#d1d4dc",
        "surface-container-lowest": "#ffffff",
        "primary": "#004be2",
        "inverse-on-surface": "#9b9da1",
        "tertiary": "#006571",
        "tertiary-dim": "#005863",
        "inverse-primary": "#6889ff",
        "on-secondary-fixed": "#3b00a0",
        "on-tertiary": "#d8f8ff",
        "on-tertiary-fixed": "#003840",
        "on-secondary": "#f7f0ff",
        "on-primary": "#f2f1ff",
        "secondary-fixed-dim": "#cabaff",
        "tertiary-container": "#00e3fd",
        "secondary-container": "#d8caff",
        "secondary-fixed": "#d8caff",
        "on-error": "#ffefef",
        "on-surface": "#2c2f33",
        "outline-variant": "#abadb2",
        "surface-container-high": "#e0e2e9",
        "on-surface-variant": "#595c60",
        "on-tertiary-fixed-variant": "#005762",
        "on-primary-fixed-variant": "#002376",
        "background": "#f5f6fb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": [ "Plus Jakarta Sans" ],
        "body": [ "Manrope" ],
        "label": [ "Manrope" ]
      }
    },
  },
  plugins: [],
};
